### ISSUE TITLE
function publishToScript (src/index.ts) seems to be extremely slow

### ISSUE THREAD

**Issue by myo** [botkalista/ayaya-league-external#17]
Events (I tested onMissileCreate) that use this are getting dispatched ~100 ms **later** than just calling script.onMissileCreate(missile, manager);

**Comment by myo** [comment]
thanks

**Comment by botkalista** [comment]
> Events (I tested onMissileCreate) that use this are getting dispatched ~100 ms **later** than just calling script.onMissileCreate(missile, manager);

The problem was caused from the surrounding `setImmediate` function that i added for debug purpose. I removed it in the last commit (https://github.com/botkalista/ayaya-league-external/commit/1275a7f524d1024097c58659faf73b2d761800ef#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)
